# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOpOBmX5-P0qqOyszhfzV953dNK1JrYi
"""

import joblib
import torch
import torch.nn as nn

def load_encoders(item_path="models/item_encoder.pkl", cat_path="models/category_encoder.pkl"):
    item_encoder = joblib.load(item_path)
    cat_encoder = joblib.load(cat_path)
    return item_encoder, cat_encoder


def pad_sequence(seq, max_len, pad_value=0):
    return seq + [pad_value] * (max_len - len(seq))